name = "NaNMath"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
repo = "https://github.com/mlubin/NaNMath.jl.git"
authors = ["Miles Lubin"]
version = "1.0.0"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
